### ISSUE TITLE
UI compilation error

### ISSUE THREAD

**Issue by lucasponce** [swift-sunshine/swsui#16]
@jotak probably it's nothing, but after your latest master I get this
![image](https://user-images.githubusercontent.com/1662329/36271466-ff4dd3a0-127e-11e8-81e1-a2fc71cdb657.png)

P.S.: For ephimeral issues on UI I open this one, if a bug is confirmed then I'd open a proper JIRA, but I find this easy for these kind of matters (typo, or a missing step in my env).

**Comment by lucasponce** [comment]
From the console:
```
(4,56): Could not find a declaration file for module 'react-router-dom'. '/home/lponce/git/swsui/node_modules/react-router-dom/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-router-dom` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-router-dom';`
****
```
Before I ran a npm install but I can't see the react-router-dom under node_modules folder. 

So, perhaps I don't remember something, but it is failing my npm or did I miss anything on my setup ?

**Comment by lucasponce** [comment]
cc @mtho11 too as I guess this could be some newbie issue from my side instead a bug, related my setup.

**Comment by mtho11** [comment]
@lucasponce I fixed this with https://github.com/swift-sunshine/swsui/pull/17
It is merged to master now.
